### ISSUE TITLE
Peer to peer morning session code review.

### ISSUE THREAD

**Issue by RuriEnciso** [demesameneshoa/Portfolio#5]
You are doing a great job !!

## Highlights
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Good code implementation ✅

Please read my suggestions below and I hope you will aply them.
## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

- Please kindly consider to add a new empty line below of your last line in CSS file, Your web page needs it to works fine in others browsers.
- Suggestion: Good practice to put all the fonts in :root and use it as a variable for example: :root { --font-roboto: "Inter", sans-serif;}

Thanks and happy coding ! 😁.

**Comment by demesameneshoa** [comment]
- Hi Team! thanks to the feedback I have updated my project based on your feedbacks and pushed on my last commmit
